apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - name: http
      nodePort: 32100
      port: 7003
      protocol: TCP
      targetPort: 7003
  selector:
    app: test1
  type: LoadBalancer
status:
  loadBalancer: {}
