apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.225.53.202
  clusterIPs:
    - 10.225.53.202
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 32100
      port: 7003
      protocol: TCP
      targetPort: 7003
  selector:
    app: test1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
